site_name: LunariLib Documentation

repo_url: https://github.com/frostx-official/
site_url: https://frostx-official.github.io/lunarilibdocs/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png

  features:
    - content.code.copy
    - navigation.tracking

  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: make your eyes burn

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - English:
      - Introduction: '/languages/en'
      - Getting Started: '/languages/en/getting-started'

    - Russian:
      - Введение: '/languages/ru'
      - Начало скриптинга: '/languages/ru/getting-started'

    - Ukrainian:
      - Вступ: '/languages/ua'
      - Початок створення скрипту: '/languages/ua/getting-started'

    - Download: '/download'

extra:
  homepage: /languages/en/

  alternate:
    - name: English
      link: /languages/en/
      lang: en

    - name: Russian
      link: /languages/ru/
      lang: ru

    - name: Ukrainian
      link: /languages/ua/
      lang: ua